site_name:        UdpTest.jl
repo_url:         https://github.com/piebat/UdpTest.jl
site_description: Demo for Julia Programming Course
site_author:      piebat

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md,
  - Code: page2.md
